# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 Oliver Lorenz
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
- name: Perform Matterbridge installation tasks
  when: matterbridge_enabled | bool
  tags:
    - setup-all
    - setup-matterbridge
    - install-all
    - install-matterbridge
  block:
    - name: Validate Matterbridge configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Matterbridge
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Matterbridge uninstallation tasks
  when: not matterbridge_enabled | bool
  tags:
    - setup-all
    - setup-matterbridge
  block:
    - name: Uninstall Matterbridge
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
