# SPDX-FileCopyrightText: 2024 Oliver Lorenz
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
- name: Check existence of Matterbridge systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ matterbridge_identifier }}.service"
  register: matterbridge_service_stat

- name: Uninstall Matterbridge systemd services and files
  when: matterbridge_service_stat.stat.exists | bool
  block:
    - name: Ensure Matterbridge systemd service is stopped
      ansible.builtin.service:
        name: "{{ matterbridge_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Matterbridge systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ matterbridge_identifier }}.service"
        state: absent

    - name: Ensure Matterbridge container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ matterbridge_container_network }}"
        state: absent

    - name: Ensure Matterbridge container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ matterbridge_container_network }}
      register: network_deletion_result
      changed_when: matterbridge_container_network in network_deletion_result.stdout

    - name: Ensure Matterbridge path does not exist
      ansible.builtin.file:
        path: "{{ matterbridge_base_path }}"
        state: absent
