# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 Oliver Lorenz
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - { "old": "matterbridge_config_dir_path", "new": "matterbridge_config_path" }
    - { "old": "matterbridge_container_registry_prefix", "new": "matterbridge_container_image_registry_prefix" }
    - { "old": "matterbridge_systemd_required_systemd_services_list_default", "new": "matterbridge_systemd_required_services_list_default" }
    - { "old": "matterbridge_systemd_required_systemd_services_list_auto", "new": "matterbridge_systemd_required_services_list_auto" }
    - { "old": "matterbridge_systemd_required_systemd_services_list_custom", "new": "matterbridge_systemd_required_services_list_custom" }
    - { "old": "matterbridge_systemd_wanted_systemd_services_list_default", "new": "matterbridge_systemd_wanted_services_list_default" }
    - { "old": "matterbridge_systemd_wanted_systemd_services_list_auto", "new": "matterbridge_systemd_wanted_services_list_auto" }
    - { "old": "matterbridge_systemd_wanted_systemd_services_list_custom", "new": "matterbridge_systemd_wanted_services_list_custom" }

- name: Fail if required Matterbridge settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - matterbridge_uid
    - matterbridge_gid
    - matterbridge_container_network
